/*

Problem Description:

A data processing pipeline consists of n services in series where the output of service i serves as input to service i+1. Each service has varying latency, and the throughput of the ith service is represented by throughput[i] in messages per minute.

Each service can be scaled up independently. Scaling up the ith service one unit of time costs scalingCost[i], and after scaling up x times, the service can process throughput[i] * (1 + x) messages per minute.

Given throughput and scalingCost arrays of size n, and a budget value, determine the optimal scaling configuration to maximize the throughput of the final service. Return the maximum throughput possible.

Illustrative Example:

Consider throughput = [4, 2, 7], scalingCost = [3, 5, 6], budget = 35.

To maximize the throughput of the final service, an optimal solution might involve scaling as follows:

Service Index | Throughput | Scale To | Times Scaled | Cost per Scaling | Total Cost
--------------|------------|----------|--------------|------------------|-----------
0             | 4          | 12       | 2            | 3                | 6
1             | 2          | 10       | 4            | 5                | 20
2             | 7          | 14       | 1            | 6                | 6
The total cost for this scaling is 6 + 20 + 6 = 32, which is within the budget of 35. The remaining budget is 35 - 32 = 3.

From these units applied in series, they generate a throughput of min(12, 10, 14) = 10 units. This is the maximum possible throughput given the budget. Hence the answer is 10.

Complete the function getMaximumThroughput in the editor below.

The function getMaximumThroughput has the following parameters:

int throughput[n]: the throughput generated by each of the n services
int scalingCost[n]: the cost of scaling up a service one time
int budget: the available money
Returns
long int: the maximum value of the throughput generated at the end of the composite service after scaling within the budget.

Examples
Example 1: (Sample Case 0)
Input:
n = 3
throughput = [3, 2, 5]
scalingCost = [2, 5, 10]
budget = 28

Output:
6
Explanation: The optimal scaling configuration to achieve maximum throughput within the budget is:

Service Index | Throughput | Scale To | Times Scaled | Cost per Scaling | Total Cost
--------------|------------|----------|--------------|------------------|-----------
0             | 3          | 15       | 4            | 2                | 8
1             | 2          | 6        | 2            | 5                | 10
2             | 5          | 10       | 1            | 10               | 10
The total cost is 8 + 10 + 10 = 28, which exactly matches the budget. The final throughput is min(15, 6, 10) = 6.

Constraints
1 <= n <= 105
1 <= throughput[i] <= 107
1 <= scalingCost[i] <= 200
1 <= budget <= 109
It is guaranteed that the answer, i.e., the maximum throughput value at the end of the n services is <= 109.
Input Format For Custom Testing
The first line contains an integer, n, the number of elements in throughput.

The next line contains n integers, throughput[0], throughput[1], ..., throughput[n-1].

The next line contains an integer, n, the number of elements in scalingCost.

The next line contains n integers, scalingCost[0], scalingCost[1], ..., scalingCost[n-1].

The next line contains an integer, budget.

Function Signature:






https://oahelper.in/questions/U2FsdGVkX19Rkz8oku1NpQAIUGP8haEGc74dF3kjy-4?company_id=U2FsdGVkX18k7ePcCv1frLB_pdqNNAuX2NKNwHqVshU


`terminologies:`

1. `throughput`:->  how much work or service processed per unit time

2. Since the services are in series (output of one is input of next):

3.   Important Point

Since all services are in series →
poori pipeline ki speed = sabse slow service ki speed


*/








#include <bits/stdc++.h>
using namespace std;


void setupIO() {
    ios::sync_with_stdio(false); cin.tie(nullptr);
    #ifndef ONLINE_JUDGE
        freopen("input.txt", "r", stdin);
        freopen("output.txt", "w", stdout);
    #endif
}


bool canAchieve(long long T, const vector<int>& throughput, const vector<int>& scalingCost, long long budget) {
    long long totalCost = 0;
    int n = throughput.size();
    
    for (int i = 0; i < n; i++) {
        if (throughput[i] >= T) continue; // no scaling needed

        // Calculate how many scale-ups needed
        long long required = ((T + throughput[i] - 1) / throughput[i]) -1 ; 
        totalCost += required * 1LL * scalingCost[i];
        
        if (totalCost > budget) return false; // early break
    }
    return totalCost <= budget;
}

long long getMaximumThroughput(vector<int>& throughput, vector<int>& scalingCost, long long budget) {
    long long low = *min_element(throughput.begin(), throughput.end());
    long long high = 1e9;
    long long ans = low;

    while (low <= high) {
        long long mid = (low + high) / 2;
        if (canAchieve(mid, throughput, scalingCost, budget)) {
            ans = mid;
            low = mid + 1; // try higher
        } else {
            high = mid - 1; // try lower
        }
    }
    return ans;
}

int main() {  setupIO();
    int n;
    cin >> n;
    vector<int> throughput(n), scalingCost(n);
    for (int i = 0; i < n; i++) cin >> throughput[i];
    for (int i = 0; i < n; i++) cin >> scalingCost[i];
    long long budget;
    cin >> budget;

    cout << getMaximumThroughput(throughput, scalingCost, budget) << endl;

    return 0;
}
